create table doctor (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    crm VARCHAR(7) NOT NULL,
    phone VARCHAR(10),
    cellphone VARCHAR(11) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    specialty ENUM('ALERGOLOGIA','ANGIOLOGIA','BUCO MAXILO', 'CARDIOLOGIA CLÍNICA', 'CARDIOLOGIA INFANTIL', 'CIRURGIA CABEÇA E PESCOÇO', 'CIRURGIA CARDÍACA', 'CIRURGIA DE TÓRAX') NOT NULL
);